Controllers/KorpusaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PCConfigurator.Data;
using PCConfigurator.Models;
using System.Threading.Tasks;

namespace PCConfigurator.Controllers
{
    /// <summary>
    /// Контроллер для управления корпусами
    /// </summary>
    public class KorpusaController : Controller
    {
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Конструктор контроллера корпусов
        /// </summary>
        /// <param name="context">Контекст базы данных</param>
        public KorpusaController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Отображает список всех корпусов
        /// </summary>
        /// <returns>Представление со списком корпусов</returns>
        public async Task<IActionResult> Index()
        {
            var korpusa = await _context.Korpusa.ToListAsync();
            return View(korpusa);
        }

        /// <summary>
        /// Отображает детальную информацию о корпусе
        /// </summary>
        /// <param name="id">Модель корпуса</param>
        /// <returns>Представление с детальной информацией</returns>
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korpus = await _context.Korpusa
                .FirstOrDefaultAsync(m => m.Model == id);
            
            if (korpus == null)
            {
                return NotFound();
            }

            return View(korpus);
        }

        /// <summary>
        /// Отображает форму для создания нового корпуса
        /// </summary>
        /// <returns>Представление формы создания</returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Обрабатывает данные из формы создания корпуса
        /// </summary>
        /// <param name="korpus">Данные корпуса</param>
        /// <returns>Перенаправление на список корпусов</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Model,PodderzhivayemyyeFormFaktory,Razmery,Tsena")] Korpus korpus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(korpus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(korpus);
        }

        /// <summary>
        /// Отображает форму для редактирования корпуса
        /// </summary>
        /// <param name="id">Модель корпуса</param>
        /// <returns>Представление формы редактирования</returns>
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korpus = await _context.Korpusa.FindAsync(id);
            if (korpus == null)
            {
                return NotFound();
            }
            return View(korpus);
        }

        /// <summary>
        /// Обрабатывает данные из формы редактирования корпуса
        /// </summary>
        /// <param name="id">Модель корпуса</param>
        /// <param name="korpus">Обновленные данные корпуса</param>
        /// <returns>Перенаправление на список корпусов</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Model,PodderzhivayemyyeFormFaktory,Razmery,Tsena")] Korpus korpus)
        {
            if (id != korpus.Model)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(korpus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KorpusExists(korpus.Model))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(korpus);
        }

        /// <summary>
        /// Отображает форму подтверждения удаления корпуса
        /// </summary>
        /// <param name="id">Модель корпуса</param>
        /// <returns>Представление формы удаления</returns>
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korpus = await _context.Korpusa
                .FirstOrDefaultAsync(m => m.Model == id);
            
            if (korpus == null)
            {
                return NotFound();
            }

            return View(korpus);
        }

        /// <summary>
        /// Удаляет корпус из базы данных
        /// </summary>
        /// <param name="id">Модель корпуса</param>
        /// <returns>Перенаправление на список корпусов</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var korpus = await _context.Korpusa.FindAsync(id);
            if (korpus != null)
            {
                _context.Korpusa.Remove(korpus);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Проверяет существование корпуса
        /// </summary>
        /// <param name="id">Модель корпуса</param>
        /// <returns>True если корпус существует, иначе False</returns>
        private bool KorpusExists(string id)
        {
            return _context.Korpusa.Any(e => e.Model == id);
        }
    }
}

Controllers/NakopiteliController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PCConfigurator.Data;
using PCConfigurator.Models;
using System.Threading.Tasks;

namespace PCConfigurator.Controllers
{
    /// <summary>
    /// Контроллер для управления накопителями
    /// </summary>
    public class NakopiteliController : Controller
    {
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Конструктор контроллера накопителей
        /// </summary>
        /// <param name="context">Контекст базы данных</param>
        public NakopiteliController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Отображает список всех накопителей
        /// </summary>
        /// <returns>Представление со списком накопителей</returns>
        public async Task<IActionResult> Index()
        {
            var nakopiteli = await _context.Nakopiteli.ToListAsync();
            return View(nakopiteli);
        }

        /// <summary>
        /// Отображает детальную информацию о накопителе
        /// </summary>
        /// <param name="id">Модель накопителя</param>
        /// <returns>Представление с детальной информацией</returns>
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nakopitel = await _context.Nakopiteli
                .FirstOrDefaultAsync(m => m.Model == id);
            
            if (nakopitel == null)
            {
                return NotFound();
            }

            return View(nakopitel);
        }

        /// <summary>
        /// Отображает форму для создания нового накопителя
        /// </summary>
        /// <returns>Представление формы создания</returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Обрабатывает данные из формы создания накопителя
        /// </summary>
        /// <param name="nakopitel">Данные накопителя</param>
        /// <returns>Перенаправление на список накопителей</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Model,Tip,ObyomGb,SkorostChteniyaMbS,SkorostZapisiMbS,Tsena")] Nakopitel nakopitel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nakopitel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nakopitel);
        }

        /// <summary>
        /// Отображает форму для редактирования накопителя
        /// </summary>
        /// <param name="id">Модель накопителя</param>
        /// <returns>Представление формы редактирования</returns>
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nakopitel = await _context.Nakopiteli.FindAsync(id);
            if (nakopitel == null)
            {
                return NotFound();
            }
            return View(nakopitel);
        }

        /// <summary>
        /// Обрабатывает данные из формы редактирования накопителя
        /// </summary>
        /// <param name="id">Модель накопителя</param>
        /// <param name="nakopitel">Обновленные данные накопителя</param>
        /// <returns>Перенаправление на список накопителей</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Model,Tip,ObyomGb,SkorostChteniyaMbS,SkorostZapisiMbS,Tsena")] Nakopitel nakopitel)
        {
            if (id != nakopitel.Model)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nakopitel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NakopitelExists(nakopitel.Model))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nakopitel);
        }

        /// <summary>
        /// Отображает форму подтверждения удаления накопителя
        /// </summary>
        /// <param name="id">Модель накопителя</param>
        /// <returns>Представление формы удаления</returns>
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nakopitel = await _context.Nakopiteli
                .FirstOrDefaultAsync(m => m.Model == id);
            
            if (nakopitel == null)
            {
                return NotFound();
            }

            return View(nakopitel);
        }

        /// <summary>
        /// Удаляет накопитель из базы данных
        /// </summary>
        /// <param name="id">Модель накопителя</param>
        /// <returns>Перенаправление на список накопителей</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var nakopitel = await _context.Nakopiteli.FindAsync(id);
            if (nakopitel != null)
            {
                _context.Nakopiteli.Remove(nakopitel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Проверяет существование накопителя
        /// </summary>
        /// <param name="id">Модель накопителя</param>
        /// <returns>True если накопитель существует, иначе False</returns>
        private bool NakopitelExists(string id)
        {
            return _context.Nakopiteli.Any(e => e.Model == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Конфигуратор ПК</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <style>
        .table-header-custom {
            background-color: #503fbe !important;
            color: rgb(13, 12, 102) !important;
        }
        
        .table-header-custom th {
            color: rgb(23, 10, 121) !important;
            font-weight: bold;
        }
        
        .navbar-custom {
            background-color: #230f98 !important;
        }
        
        .footer-custom {
            background-color: #343a40 !important;
            color: white !important;
        }
        
        .card-header-custom {
            background-color: #6c757d !important;
            color: white !important;
            border: none !important;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark navbar-custom border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-pc-display"></i> Конфигуратор ПК
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="bi bi-house"></i> Главная
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="componentsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-motherboard"></i> Компоненты
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="componentsDropdown">
                                <li><a class="dropdown-item" asp-controller="MaterinskiyePlaty" asp-action="Index">Материнские платы</a></li>
                                <li><a class="dropdown-item" asp-controller="Protsessory" asp-action="Index">Процессоры</a></li>
                                <li><a class="dropdown-item" asp-controller="OperativnayaPamyat" asp-action="Index">Оперативная память</a></li>
                                <li><a class="dropdown-item" asp-controller="Videokarty" asp-action="Index">Видеокарты</a></li>
                                <li><a class="dropdown-item" asp-controller="Nakopiteli" asp-action="Index">Накопители</a></li>
                                <li><a class="dropdown-item" asp-controller="BlokiPitaniya" asp-action="Index">Блоки питания</a></li>
                                <li><a class="dropdown-item" asp-controller="Korpusa" asp-action="Index">Корпуса</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="GotovyyeSborki" asp-action="Index">
                                <i class="bi bi-gear"></i> Готовые сборки
                            </a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer footer-custom text-white">
        <div class="container text-center">
            &copy; 2026 - Конфигуратор ПК
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>